version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: kochetov/backend-project-v4
    command: bash -c 'npm run test'

  frontend:
    build:
      context: .
      dockerfile: kochetov/backend-project-v4
    restart: always
    depends_on: [backend]

