FROM node:18-slim

RUN apt-get update && apt-get install -yq \
  build-essential \
  python3

RUN ln -s /usr/bin/python3 /usr/bin/python

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN make setup

CMD ["bash", "-c", "make start-backend | make start-frontend"]


