version: '3'

services:
  app:
    environment:
      - NODE_ENV=development
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: bash -c 'make setup && make start-backend && make start-frontend'
    ports:
      - "3000:3000"
