version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: kochetov/backend-project-v4
    environment:
      NODE_ENV: test
      SESSION_KEY: ${SESSION_KEY}
      ROLLBAR_TOKEN: ${ROLLBAR_TOKEN}
    command: bash -c 'npm run test'
