version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: bash -c 'npm run test'

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.production
    restart: always
    depends_on: [backend]
