FROM node:18-slim

RUN apt-get update && apt-get install -yq \
  build-essential \
  python3

RUN ln -s /usr/bin/python3 /usr/bin/python

WORKDIR /app

COPY package.json /app
COPY package-lock.json /app

RUN npm ci

COPY . .

ENV NODE_ENV=production
RUN npm run build

CMD ["bash", "-c", "npx knex migrate:latest && npm start"]
