name: Heroku deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.6.8
      with:
        HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        HEROKU_APP_NAME: "site-task-manager"
        HEROKU_EMAIL: "evgkochz@gmail.com"
      env:
        HD_ROLLBAR_API_KEY: ${{secrets.ROLLBAR_API_KEY}}
    - name: Run a one-line script
      run: echo successfully run
