name: Pull_Request

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v2

      - name: Set environment variables
        run: echo "SESSION_KEY=${{ secrets.SESSION_KEY }}" >> $GITHUB_ENV

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: test
        run: make ci
      - name: Lint
        run: make lint
